
export enum CategoriesEvent {
    ART_CULTURES = 'ART_CULTURES',
    HOBBIES = 'HOBBIES',
    TRAVEL = 'TRAVEL',
    FITNESS_HEALTH = 'FITNESS_HEALTH',
    SPIRITUALITY = 'SPIRITUALITY',
    SOCIAL = 'SOCIAL',
    CHARITY = 'CHARITY',
    BUSINESS = 'BUSINESS',
    EDUCATION = 'EDUCATION',
    FOOD_DRINKS = 'FOOD_DRINKS',
}